In [ ]:
importance normalize 


In [39]:
import src.datasets as datasets


In [40]:
import src.surrogate as surrogate


In [41]:
load_data_func = getattr(datasets, f'cement_data')

In [42]:
X_train, X_test, y_train, y_test = load_data_func('./data/concrete_processed.csv')

In [43]:
load_data_loader_func = getattr(datasets, f'lightgbm_load_data')

In [44]:
train_loader, val_loader = load_data_loader_func(X_train, X_test, y_train, y_test)

In [45]:
train_func = getattr(surrogate, f'lightgbm_train')

In [46]:
model = train_func(train_loader, val_loader)

/opt/conda/lib/python3.10/site-packages/lightgbm/basic.py:357: UserWarning: Converting column-vector to 1d array
  _log_warning("Converting column-vector to 1d array")


Training until validation scores don't improve for 50 rounds
[100]	train's rmse: 0.0448095	valid's rmse: 0.0588017
[200]	train's rmse: 0.0342117	valid's rmse: 0.0521947
[300]	train's rmse: 0.0290689	valid's rmse: 0.050235
Early stopping, best iteration is:
[305]	train's rmse: 0.0288801	valid's rmse: 0.0501455


In [47]:
['cement','slag','ash','water','superplastic','coarseagg','fineagg','age','strength']


['cement',
 'slag',
 'ash',
 'water',
 'superplastic',
 'coarseagg',
 'fineagg',
 'age',
 'strength']

In [48]:
model.feature_importance() / model.feature_importance().sum()

array([0.16851574, 0.10224888, 0.06521739, 0.14767616, 0.1191904 ,
       0.14137931, 0.16521739, 0.09055472])

In [49]:
import fireducks.pandas as pd

In [50]:
df = pd.DataFrame()

In [51]:
df['column_name'] = ['cement','slag','ash','water','superplastic','coarseagg','fineagg','age']

In [52]:
df

column_name
0        cement
1          slag
2           ash
3         water
4  superplastic
5     coarseagg
6       fineagg
7           age

In [53]:
df['importance'] = model.feature_importance() / model.feature_importance().sum()

In [54]:
df

column_name  importance
0        cement    0.168516
1          slag    0.102249
2           ash    0.065217
3         water    0.147676
4  superplastic    0.119190
5     coarseagg    0.141379
6       fineagg    0.165217
7           age    0.090555

In [55]:
df.to_csv('./feature_importance.csv')

In [56]:
['cement','slag','ash','water','coarseagg','fineagg','age']

['cement', 'slag', 'ash', 'water', 'coarseagg', 'fineagg', 'age']

In [65]:
import numpy as np

In [66]:
np.concatenate([X_train[:7,0],X_train[:7,0]])

array([0.11643836, 0.48242009, 0.25776256, 0.73515982, 0.14155251,
       0.88812785, 0.73744292, 0.11643836, 0.48242009, 0.25776256,
       0.73515982, 0.14155251, 0.88812785, 0.73744292])

In [68]:
df = pd.DataFrame()


In [69]:
df['id'] = [1]*7 + [2]*7
df['column_name'] = ['cement','slag','ash','water','coarseagg','fineagg','age']*2
df['ground_truth'] = np.concatenate([X_train[:7,0],X_train[:7,0]])
df['predicted'] = np.concatenate([X_test[:7,0],X_test[:7,1]])


In [70]:
df

id column_name  ground_truth  predicted
0    1      cement      0.116438   0.107306
1    1        slag      0.482420   0.146347
2    1         ash      0.257763   0.481735
3    1       water      0.735160   0.130137
4    1   coarseagg      0.141553   0.149315
5    1     fineagg      0.888128   0.223744
6    1         age      0.737443   0.769406
7    2      cement      0.116438   0.406314
8    2        slag      0.482420   0.000000
9    2         ash      0.257763   0.423853
10   2       water      0.735160   0.435545
11   2   coarseagg      0.141553   0.379714
12   2     fineagg      0.888128   0.388775
13   2         age      0.737443   0.517393

In [ ]:
df['column_name'] = ['cement','slag','ash','water','coarseagg','fineagg','age']
df['ground_truth'] = X_train[:7,0]
df['predicted'] = X_test[:7,0]
# df.to_csv('./feature_importance.csv')


In [58]:
df

column_name  ground_truth  predicted
0      cement      0.116438   0.107306
1        slag      0.482420   0.146347
2         ash      0.257763   0.481735
3       water      0.735160   0.130137
4   coarseagg      0.141553   0.149315
5     fineagg      0.888128   0.223744
6         age      0.737443   0.769406

In [71]:
df.to_csv('./search_space.csv')

In [60]:
X_train[:7,0]

array([0.11643836, 0.48242009, 0.25776256, 0.73515982, 0.14155251,
       0.88812785, 0.73744292])